version: '{build}'
skip_tags: true
clone_depth: 10
clone_folder: C:\projects\CodeOrchestra\colt-build
environment:
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
build_script:
  - cd C:\projects\CodeOrchestra\colt-build
  - copy gradle.properties.sample gradle.properties
  - gradlew
  - gradle build
